print("arun")
print("age = 21")
print("hi")
print("emor")
print("phis")
print("route53")
print("vpc")
print("ec2")
print("elasticbeanstack")
print("cloudwatch")
print("elasticblockstorage")
print("public subnet")
print("private subnet")
print("key-pair")


